language: java
install: ant jar

deploy:
  provider: releases
  api_key:
    secure: kOoLXyg1tq1ohSay07491dmDirygNIJvXw6scd1Ih1RCUsTvKdGXM10qDd+JuLRJXwAcyRayqBdT684QRzoNd/Sl3/od15ohYLXxPukiZ9BXqF94V9eHYzPvKvT+xHC2BsZhiHYdP088f+sgRxtgamIMOZysMNCOz6kqxdiZW16whxn2/z2gGSw4lnFwKbhvohrAuO9eVGgZOMlwpF+46xKkkkcLhSk9goNjn08XzrahqM76VG/KO38zOm6ySFpLu3PmONT5bK5+obeeBTK9ScbSFvi4z6lghpiyRxnqOzZ2zV1alYeLkZd4SnZe7THqSXxP41/b776OwOkPqbvklUEgo6R5VliCQKuPl1YjHHZ7M6BAHHnAhaWZoI6L3m7FM3toK8XKJ8sqhgj2AIk9RMZCAmx2E1IPDBPSYJh5N9P8/a60FALTcaj/DddhO00osc8k5ee2jq7PclwCYOGo9mVhz+v6OdeIiBq9K/dsDJWFlVZPRAUf2ztwIoEiJ4F5DT6TfrBzwkcqtJOydMY3rkqhI0o/j1MEAu3GFWdEyXOTeWW7MDGsBKd5AWsGOGzD7VmJf1p5f2u1o5Jpl/iZ0NxuxDplRNEqClIEqNJlUe6zP6+MfeJu4A/XluXTPEwpsYwzKXGxzMDDV+g7zOG4GzUOg7RA8GiAdXj7en6FL+M=
  file: out/EchecMartien.jar
  on:
    repo: EnzDev/EchecMartiens
